### PR TITLE
WIP: Update Layout

### PR DESCRIPTION
**Pull request by cykler**

### CODE REVIEW

**Comment by maxrimue** [comment]
I did a few organizational things to make working with the Sketch file easier. We should settle for a definitive structure (screens/workflow) and then get this merged soon. Stylistic changes are easier to adapt and are not necessary for core functionality.

What I also recommend us to be doing is to revise the Game view. I will create a separate ticket for this in which I describe what I mean.

**Comment by maxrimue** [comment]
I added a Sketch file containing a few logo concepts I've made, here they are as of right now:
Test One
Test Two
Test Three
Test Four
Test Five
Test Six
Test Seven
Test Eight

**Comment by cykler** [comment]
A few of them are quite nice! Let's discuss them in a co-working session.
My only concern is that we need to find something that fits nicely into our current art style.

**Comment by maxrimue** [comment]
Here's an updated version of logo idea seven:
Test Seven

**Pull request merged**
